import type { Exercise } from "./types";

export const mockExercises: Exercise[] = [
  {
    id: "exercise-meaning-match",
    type: "meaning_match",
    prompt: "Choose the best meaning.",
    instructions: "Match the word to its closest meaning.",
    target_word: "intricate",
    target_word_id: "word-intricate",
    question_text: "Which option is the best meaning of 'intricate'?",
    sentence_text: "The machine had an intricate design with many tiny moving parts.",
    sourceLanguageLabel: "English",
    targetLanguageLabel: "Meaning",
    options: [
      { id: "a", label: "highly detailed and complex" },
      { id: "b", label: "very loud" },
      { id: "c", label: "easy to notice" },
      { id: "d", label: "quickly finished" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["very loud", "easy to notice", "quickly finished"],
    pairs: [
      { id: "pair-1", left: "intricate", right: "highly detailed and complex" },
    ],
    explanation: "Intricate usually describes something with many small parts or details.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["meaning", "vocab"],
    skill: "meaning_match",
    metadata: {
      mock: true,
    },
    reviewMeta: {
      attemptCount: 0,
      streak: 0,
      dueAt: null,
    },
  },
  {
    id: "exercise-fill-blank",
    type: "fill_blank",
    prompt: "Fill in the blank.",
    instructions: "Pick the option that best completes the sentence.",
    target_word: "clear",
    target_word_id: "word-clear",
    question_text: "Which option best completes the sentence?",
    sentence_text: "The scientist gave a _____ explanation that made the process easy to follow.",
    clue: "Think about clarity.",
    options: [
      { id: "a", label: "vague" },
      { id: "b", label: "clear" },
      { id: "c", label: "hostile" },
      { id: "d", label: "minor" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["vague", "hostile", "minor"],
    explanation: "A clear explanation is easy to understand, which matches the sentence context.",
    modality: "context",
    difficulty_band: "easy",
    tags: ["cloze", "sentence"],
    skill: "fill_blank",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-translation-match-english-native",
    type: "translation_match",
    prompt: "Translate the word.",
    instructions: "Choose the native-language translation.",
    target_word: "cautious",
    target_word_id: "word-cautious",
    promptTerm: "cautious",
    sourceLanguageLabel: "English",
    targetLanguageLabel: "RU",
    translationLanguageLabel: "ru",
    direction: "english_to_native",
    question_text: "Which translation best matches 'cautious'?",
    options: [
      { id: "a", label: "осторожный" },
      { id: "b", label: "громкий" },
      { id: "c", label: "редкий" },
      { id: "d", label: "мягкий" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["громкий", "редкий", "мягкий"],
    explanation: "Cautious means careful, so the best translation is 'осторожный'.",
    modality: "text",
    difficulty_band: "easy",
    tags: ["translation", "english_to_native"],
    skill: "translation_match",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-translation-match-native-english",
    type: "translation_match",
    prompt: "Translate into English.",
    instructions: "Choose the English word that matches the translation.",
    target_word: "fragile",
    target_word_id: "word-fragile",
    promptTerm: "хрупкий",
    sourceLanguageLabel: "RU",
    targetLanguageLabel: "English",
    translationLanguageLabel: "ru",
    direction: "native_to_english",
    question_text: "Which English word matches this translation?",
    options: [
      { id: "a", label: "fragile" },
      { id: "b", label: "durable" },
      { id: "c", label: "vast" },
      { id: "d", label: "brief" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["durable", "vast", "brief"],
    explanation: "'Хрупкий' maps to the English word 'fragile'.",
    modality: "text",
    difficulty_band: "easy",
    tags: ["translation", "native_to_english"],
    skill: "translation_match",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-pair-match-translation",
    type: "pair_match",
    prompt: "Match the pairs.",
    instructions: "Tap an English word, then tap its matching translation.",
    target_word: "candid",
    target_word_id: "word-candid",
    question_text: "Match each English word to its translation.",
    options: [
      { id: "left-1", label: "candid" },
      { id: "left-2", label: "fragile" },
      { id: "left-3", label: "scarce" },
      { id: "left-4", label: "vivid" },
      { id: "right-2", label: "хрупкий" },
      { id: "right-4", label: "яркий" },
      { id: "right-1", label: "откровенный" },
      { id: "right-3", label: "редкий" },
    ],
    pairs: [
      {
        id: "pair-1",
        left: "candid",
        right: "откровенный",
        left_id: "left-1",
        right_id: "right-1",
      },
      {
        id: "pair-2",
        left: "fragile",
        right: "хрупкий",
        left_id: "left-2",
        right_id: "right-2",
      },
      {
        id: "pair-3",
        left: "scarce",
        right: "редкий",
        left_id: "left-3",
        right_id: "right-3",
      },
      {
        id: "pair-4",
        left: "vivid",
        right: "яркий",
        left_id: "left-4",
        right_id: "right-4",
      },
    ],
    correct_answer:
      "candid -> откровенный | fragile -> хрупкий | scarce -> редкий | vivid -> яркий",
    acceptable_answers: [
      "left-1::right-1",
      "left-2::right-2",
      "left-3::right-3",
      "left-4::right-4",
    ],
    distractors: ["хрупкий", "редкий", "яркий"],
    explanation: "Each English word should be paired with its closest translation.",
    modality: "text",
    difficulty_band: "easy",
    left_column_label: "English",
    right_column_label: "RU",
    variant: "english_native",
    tags: ["pair_match", "translation", "rapid_review"],
    skill: "pair_match",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-fill-blank-context-clue",
    type: "fill_blank",
    prompt: "Fill in the blank.",
    instructions: "Use the sentence and the extra context clue.",
    target_word: "reluctant",
    target_word_id: "word-reluctant",
    question_text: "Which option best fits once you consider the broader context?",
    sentence_text: "Even after several reminders, Maya was still _____ to speak first in front of the group.",
    contextHint: "She kept looking down and hoping someone else would volunteer.",
    variant: "context_clue",
    options: [
      { id: "a", label: "eager" },
      { id: "b", label: "reluctant" },
      { id: "c", label: "formal" },
      { id: "d", label: "brief" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["eager", "formal", "brief"],
    explanation: "The extra clue shows hesitation, so 'reluctant' is the best fit.",
    modality: "context",
    difficulty_band: "hard",
    tags: ["cloze", "context_clue"],
    skill: "fill_blank",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-sentence-builder",
    type: "sentence_builder",
    prompt: "Build the sentence.",
    instructions: "Tap the tiles to rebuild the sentence in the correct order.",
    target_word: "meticulous",
    target_word_id: "word-meticulous",
    question_text: 'Build the sentence that uses "meticulous" naturally.',
    sentence_text: "The meticulous editor reviewed every line twice.",
    options: [
      { id: "tile-3", label: "editor" },
      { id: "tile-1", label: "The" },
      { id: "tile-5", label: "every" },
      { id: "tile-4", label: "reviewed" },
      { id: "tile-2", label: "meticulous" },
      { id: "tile-6", label: "line" },
      { id: "tile-7", label: "twice." },
    ],
    correct_answer: "The meticulous editor reviewed every line twice.",
    acceptable_answers: ["The meticulous editor reviewed every line twice."],
    correct_sequence: [
      "tile-1",
      "tile-2",
      "tile-3",
      "tile-4",
      "tile-5",
      "tile-6",
      "tile-7",
    ],
    distractors: ["careless", "brief", "line"],
    explanation:
      'The natural sentence order is "The meticulous editor reviewed every line twice."',
    modality: "context",
    difficulty_band: "hard",
    tileStyle: "word_bank",
    clue: "Meaning clue: very careful and precise.",
    tags: ["sentence_builder", "syntax"],
    skill: "sentence_builder",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-error-detection",
    type: "error_detection",
    prompt: "Find the language error.",
    instructions: "Choose the part of the sentence that should be revised.",
    target_word: "meticulous",
    target_word_id: "word-meticulous",
    question_text: "Which part of the sentence should be revised?",
    sentence_text: "The brief editor reviewed every line twice before publication.",
    sentence_segments: [
      { id: "segment-1", text: "The" },
      { id: "segment-2", text: "brief" },
      { id: "segment-3", text: "editor reviewed every line twice before publication." },
    ],
    options: [
      { id: "segment-1", label: "The" },
      { id: "segment-2", label: "brief" },
      { id: "segment-3", label: "editor reviewed every line twice before publication." },
    ],
    correct_answer: "segment-2",
    acceptable_answers: ["segment-2"],
    distractors: ["brief", "publication", "line"],
    explanation:
      'The sentence becomes strongest when "brief" is replaced with "meticulous".',
    replacement_text: "meticulous",
    modality: "context",
    difficulty_band: "hard",
    tags: ["error_detection", "sat_style", "precision"],
    skill: "error_detection",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-error-detection-no-error",
    type: "error_detection",
    prompt: "Find the language error.",
    instructions: "Choose the part that needs revision, or select no error.",
    target_word: "concise",
    target_word_id: "word-concise",
    question_text: "Which part of the sentence should be revised?",
    sentence_text: "Her concise summary helped the committee reach a decision quickly.",
    sentence_segments: [
      { id: "segment-1", text: "Her concise summary" },
      { id: "segment-2", text: "helped the committee" },
      { id: "segment-3", text: "reach a decision quickly." },
    ],
    options: [
      { id: "segment-1", label: "Her concise summary" },
      { id: "segment-2", label: "helped the committee" },
      { id: "segment-3", label: "reach a decision quickly." },
      { id: "no_error", label: "No error" },
    ],
    correct_answer: "no_error",
    acceptable_answers: ["no_error"],
    distractors: ["summary", "committee", "quickly"],
    explanation: "No revision is needed because the sentence is already clear and precise.",
    allow_no_error: true,
    variant: "no_error_possible",
    modality: "context",
    difficulty_band: "hard",
    tags: ["error_detection", "sat_style", "no_error"],
    skill: "error_detection",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-listen-match",
    type: "listen_match",
    prompt: "Listen and match the word.",
    instructions: "Play the audio and choose the word you hear.",
    target_word: "meticulous",
    target_word_id: "word-meticulous",
    question_text: "Which option matches the audio prompt?",
    sentence_text: "The editor was meticulous and checked every detail twice.",
    options: [
      { id: "a", label: "meticulous" },
      { id: "b", label: "casual" },
      { id: "c", label: "fragile" },
      { id: "d", label: "outcome" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["casual", "fragile", "outcome"],
    explanation:
      "Meticulous means very careful and precise, which fits the detail-focused context.",
    modality: "audio",
    difficulty_band: "easy",
    tags: ["audio", "recognition"],
    skill: "listen_match",
    audio_url:
      "data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=",
    audio_status: "ready",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-spelling-from-audio",
    type: "spelling_from_audio",
    prompt: "Listen and spell the word.",
    instructions: "Play the audio and type the spelling from memory.",
    target_word: "cautious",
    target_word_id: "word-cautious",
    question_text: "Type the word you hear.",
    sentence_text: "The hikers were cautious as they crossed the narrow bridge.",
    options: [],
    correct_answer: "cautious",
    acceptable_answers: ["cautious"],
    distractors: ["careful", "bridge", "narrow"],
    explanation: "Cautious is spelled c-a-u-t-i-o-u-s and means careful to avoid danger.",
    modality: "audio",
    difficulty_band: "medium",
    tags: ["audio", "spelling"],
    skill: "spelling_from_audio",
    placeholder: "Type what you heard",
    inputLabel: "Spell the word",
    audio_url:
      "data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=",
    audio_status: "ready",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-context-meaning",
    type: "context_meaning",
    prompt: "What does the highlighted word mean in context?",
    instructions: "Use the sentence, not just the dictionary meaning.",
    target_word: "rugged",
    target_word_id: "word-rugged",
    question_text: "What does 'rugged' mean in this sentence?",
    sentence_text:
      "Although the road looked smooth from a distance, the hikers quickly realized it was rugged and difficult to cross.",
    contextText:
      "Although the road looked smooth from a distance, the hikers quickly realized it was rugged and difficult to cross.",
    focusText: "rugged",
    options: [
      { id: "a", label: "stylish" },
      { id: "b", label: "rough and uneven" },
      { id: "c", label: "covered in water" },
      { id: "d", label: "narrow and crowded" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["stylish", "covered in water", "narrow and crowded"],
    explanation: "The clue is 'difficult to cross,' which points to rough ground.",
    modality: "context",
    difficulty_band: "hard",
    tags: ["context", "meaning"],
    skill: "context_meaning",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-context-meaning-fragile",
    type: "context_meaning",
    prompt: "What does the highlighted word mean in context?",
    instructions: "Use the surrounding clues to infer the best meaning.",
    target_word: "fragile",
    target_word_id: "word-fragile",
    question_text: "What does 'fragile' mean in this sentence?",
    sentence_text:
      "The museum staff handled the fragile vase with special gloves because one small mistake could shatter it.",
    contextText:
      "The museum staff handled the fragile vase with special gloves because one small mistake could shatter it.",
    focusText: "fragile",
    options: [
      { id: "a", label: "easily broken" },
      { id: "b", label: "brightly painted" },
      { id: "c", label: "extremely old" },
      { id: "d", label: "stored outdoors" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["brightly painted", "extremely old", "stored outdoors"],
    explanation: "The clue is 'could shatter it,' so fragile means easily broken.",
    modality: "context",
    difficulty_band: "medium",
    tags: ["context", "meaning"],
    skill: "context_meaning",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-synonym",
    type: "synonym",
    prompt: "Choose the closest synonym.",
    instructions: "Pick the word with the nearest meaning.",
    target_word: "abandon",
    target_word_id: "word-abandon",
    question_text: "Which option is the closest synonym for 'abandon'?",
    sentence_text: "They had to abandon the plan after the storm changed direction.",
    options: [
      { id: "a", label: "leave behind" },
      { id: "b", label: "repair" },
      { id: "c", label: "balance" },
      { id: "d", label: "measure" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["repair", "balance", "measure"],
    explanation: "Abandon means to leave something behind or give it up.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["synonym"],
    skill: "synonym",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-synonym-brief",
    type: "synonym",
    prompt: "Choose the closest synonym.",
    instructions: "Pick the substitute with the nearest meaning.",
    target_word: "brief",
    target_word_id: "word-brief",
    question_text: "Which option is the closest synonym for 'brief'?",
    sentence_text: "The manager gave a brief update before the meeting moved on.",
    options: [
      { id: "a", label: "short" },
      { id: "b", label: "confusing" },
      { id: "c", label: "private" },
      { id: "d", label: "formal" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["confusing", "private", "formal"],
    explanation: "Brief means short in length or duration.",
    modality: "text",
    difficulty_band: "easy",
    tags: ["synonym"],
    skill: "synonym",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-antonym-expand",
    type: "synonym",
    prompt: "Choose the clearest opposite.",
    instructions: "Pick the option with the opposite meaning.",
    target_word: "expand",
    target_word_id: "word-expand",
    question_text: "Which option is the best antonym for 'expand'?",
    sentence_text: "The company planned to expand into two new cities next year.",
    options: [
      { id: "a", label: "grow larger" },
      { id: "b", label: "shrink" },
      { id: "c", label: "advertise" },
      { id: "d", label: "observe" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["grow larger", "advertise", "observe"],
    explanation: "Expand means grow; the clearest opposite is shrink.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["antonym"],
    skill: "synonym",
    variant: "antonym",
    promptStyle: "best_antonym",
    metadata: { mock: true },
    reviewMeta: {},
  },
  {
    id: "exercise-collocation",
    type: "collocation",
    prompt: "Choose the most natural collocation.",
    instructions: "Pick the phrase that sounds most natural in English.",
    target_word: "summary",
    target_word_id: "word-summary",
    question_text: "Which option forms the most natural collocation?",
    sentence_text: "The teacher asked everyone to make a quick summary before class ended.",
    stem: "make a ____",
    exampleSentence: "The teacher asked everyone to make a quick summary before class ended.",
    options: [
      { id: "a", label: "summary" },
      { id: "b", label: "weather" },
      { id: "c", label: "silenceful" },
      { id: "d", label: "arrivaling" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["weather", "silenceful", "arrivaling"],
    pairs: [{ id: "pair-1", left: "make", right: "summary" }],
    explanation: "Make a summary is a natural verb-noun pairing here.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["collocation"],
    skill: "collocation",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-collocation-deep-concern",
    type: "collocation",
    prompt: "Choose the most natural collocation.",
    instructions: "Pick the word that completes the natural English phrase.",
    target_word: "concern",
    target_word_id: "word-concern",
    question_text: "Which option forms the most natural collocation?",
    sentence_text: "Residents expressed deep concern after the river level rose again overnight.",
    stem: "deep ____",
    exampleSentence:
      "Residents expressed deep concern after the river level rose again overnight.",
    options: [
      { id: "a", label: "concern" },
      { id: "b", label: "window" },
      { id: "c", label: "arrival" },
      { id: "d", label: "texture" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["window", "arrival", "texture"],
    explanation: "Deep concern is a natural and common collocation in English.",
    modality: "mixed",
    difficulty_band: "medium",
    tags: ["collocation"],
    skill: "collocation",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-collocation-pair-selection",
    type: "collocation",
    prompt: "Choose the most natural phrase partner.",
    instructions: "Complete the pair with the strongest natural fit.",
    target_word: "concern",
    target_word_id: "word-concern",
    question_text: 'Which option best completes the natural pair "deep ____"?',
    sentence_text: "Residents expressed deep concern after the river level rose again overnight.",
    stem: "deep ____",
    pairLead: "deep",
    variant: "pair_selection",
    exampleSentence:
      "Residents expressed deep concern after the river level rose again overnight.",
    options: [
      { id: "a", label: "concern" },
      { id: "b", label: "window" },
      { id: "c", label: "arrival" },
      { id: "d", label: "texture" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["window", "arrival", "texture"],
    explanation: "Deep concern is a common and natural English collocation.",
    modality: "mixed",
    difficulty_band: "hard",
    tags: ["collocation", "pair_selection"],
    skill: "collocation",
    metadata: { mock: true },
    reviewMeta: {},
  },
];
