import type { Exercise } from "./types";

export const mockExercises: Exercise[] = [
  {
    id: "exercise-meaning-match",
    type: "meaning_match",
    prompt: "Choose the best meaning.",
    instructions: "Match the word to its closest meaning.",
    target_word: "intricate",
    target_word_id: "word-intricate",
    question_text: "Which option is the best meaning of 'intricate'?",
    sentence_text: "The machine had an intricate design with many tiny moving parts.",
    sourceLanguageLabel: "English",
    targetLanguageLabel: "Meaning",
    options: [
      { id: "a", label: "highly detailed and complex" },
      { id: "b", label: "very loud" },
      { id: "c", label: "easy to notice" },
      { id: "d", label: "quickly finished" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["very loud", "easy to notice", "quickly finished"],
    pairs: [
      { id: "pair-1", left: "intricate", right: "highly detailed and complex" },
    ],
    explanation: "Intricate usually describes something with many small parts or details.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["meaning", "vocab"],
    skill: "meaning_match",
    metadata: {
      mock: true,
    },
    reviewMeta: {
      attemptCount: 0,
      streak: 0,
      dueAt: null,
    },
  },
  {
    id: "exercise-fill-blank",
    type: "fill_blank",
    prompt: "Fill in the blank.",
    instructions: "Pick the option that best completes the sentence.",
    target_word: "clear",
    target_word_id: "word-clear",
    question_text: "Which option best completes the sentence?",
    sentence_text: "The scientist gave a _____ explanation that made the process easy to follow.",
    clue: "Think about clarity.",
    options: [
      { id: "a", label: "vague" },
      { id: "b", label: "clear" },
      { id: "c", label: "hostile" },
      { id: "d", label: "minor" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["vague", "hostile", "minor"],
    explanation: "A clear explanation is easy to understand, which matches the sentence context.",
    modality: "context",
    difficulty_band: "easy",
    tags: ["cloze", "sentence"],
    skill: "fill_blank",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-listen-match",
    type: "listen_match",
    prompt: "Listen and match the word.",
    instructions: "Play the audio and choose the word you hear.",
    target_word: "meticulous",
    target_word_id: "word-meticulous",
    question_text: "Which option matches the audio prompt?",
    sentence_text: "The editor was meticulous and checked every detail twice.",
    options: [
      { id: "a", label: "meticulous" },
      { id: "b", label: "casual" },
      { id: "c", label: "fragile" },
      { id: "d", label: "outcome" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["casual", "fragile", "outcome"],
    explanation:
      "Meticulous means very careful and precise, which fits the detail-focused context.",
    modality: "audio",
    difficulty_band: "easy",
    tags: ["audio", "recognition"],
    skill: "listen_match",
    audio_url:
      "data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=",
    audio_status: "ready",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-spelling-from-audio",
    type: "spelling_from_audio",
    prompt: "Listen and spell the word.",
    instructions: "Play the audio and type the spelling from memory.",
    target_word: "cautious",
    target_word_id: "word-cautious",
    question_text: "Type the word you hear.",
    sentence_text: "The hikers were cautious as they crossed the narrow bridge.",
    options: [],
    correct_answer: "cautious",
    acceptable_answers: ["cautious"],
    distractors: ["careful", "bridge", "narrow"],
    explanation: "Cautious is spelled c-a-u-t-i-o-u-s and means careful to avoid danger.",
    modality: "audio",
    difficulty_band: "medium",
    tags: ["audio", "spelling"],
    skill: "spelling_from_audio",
    placeholder: "Type what you heard",
    inputLabel: "Spell the word",
    audio_url:
      "data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=",
    audio_status: "ready",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-context-meaning",
    type: "context_meaning",
    prompt: "What does the highlighted word mean in context?",
    instructions: "Use the sentence, not just the dictionary meaning.",
    target_word: "rugged",
    target_word_id: "word-rugged",
    question_text: "What does 'rugged' mean in this sentence?",
    sentence_text:
      "Although the road looked smooth from a distance, the hikers quickly realized it was rugged and difficult to cross.",
    contextText:
      "Although the road looked smooth from a distance, the hikers quickly realized it was rugged and difficult to cross.",
    focusText: "rugged",
    options: [
      { id: "a", label: "stylish" },
      { id: "b", label: "rough and uneven" },
      { id: "c", label: "covered in water" },
      { id: "d", label: "narrow and crowded" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["stylish", "covered in water", "narrow and crowded"],
    explanation: "The clue is 'difficult to cross,' which points to rough ground.",
    modality: "context",
    difficulty_band: "hard",
    tags: ["context", "meaning"],
    skill: "context_meaning",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-context-meaning-fragile",
    type: "context_meaning",
    prompt: "What does the highlighted word mean in context?",
    instructions: "Use the surrounding clues to infer the best meaning.",
    target_word: "fragile",
    target_word_id: "word-fragile",
    question_text: "What does 'fragile' mean in this sentence?",
    sentence_text:
      "The museum staff handled the fragile vase with special gloves because one small mistake could shatter it.",
    contextText:
      "The museum staff handled the fragile vase with special gloves because one small mistake could shatter it.",
    focusText: "fragile",
    options: [
      { id: "a", label: "easily broken" },
      { id: "b", label: "brightly painted" },
      { id: "c", label: "extremely old" },
      { id: "d", label: "stored outdoors" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["brightly painted", "extremely old", "stored outdoors"],
    explanation: "The clue is 'could shatter it,' so fragile means easily broken.",
    modality: "context",
    difficulty_band: "medium",
    tags: ["context", "meaning"],
    skill: "context_meaning",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-synonym",
    type: "synonym",
    prompt: "Choose the closest synonym.",
    instructions: "Pick the word with the nearest meaning.",
    target_word: "abandon",
    target_word_id: "word-abandon",
    question_text: "Which option is the closest synonym for 'abandon'?",
    sentence_text: "They had to abandon the plan after the storm changed direction.",
    options: [
      { id: "a", label: "leave behind" },
      { id: "b", label: "repair" },
      { id: "c", label: "balance" },
      { id: "d", label: "measure" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["repair", "balance", "measure"],
    explanation: "Abandon means to leave something behind or give it up.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["synonym"],
    skill: "synonym",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-synonym-brief",
    type: "synonym",
    prompt: "Choose the closest synonym.",
    instructions: "Pick the substitute with the nearest meaning.",
    target_word: "brief",
    target_word_id: "word-brief",
    question_text: "Which option is the closest synonym for 'brief'?",
    sentence_text: "The manager gave a brief update before the meeting moved on.",
    options: [
      { id: "a", label: "short" },
      { id: "b", label: "confusing" },
      { id: "c", label: "private" },
      { id: "d", label: "formal" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["confusing", "private", "formal"],
    explanation: "Brief means short in length or duration.",
    modality: "text",
    difficulty_band: "easy",
    tags: ["synonym"],
    skill: "synonym",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-collocation",
    type: "collocation",
    prompt: "Choose the most natural collocation.",
    instructions: "Pick the phrase that sounds most natural in English.",
    target_word: "summary",
    target_word_id: "word-summary",
    question_text: "Which option forms the most natural collocation?",
    sentence_text: "The teacher asked everyone to make a quick summary before class ended.",
    stem: "make a ____",
    exampleSentence: "The teacher asked everyone to make a quick summary before class ended.",
    options: [
      { id: "a", label: "summary" },
      { id: "b", label: "weather" },
      { id: "c", label: "silenceful" },
      { id: "d", label: "arrivaling" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["weather", "silenceful", "arrivaling"],
    pairs: [{ id: "pair-1", left: "make", right: "summary" }],
    explanation: "Make a summary is a natural verb-noun pairing here.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["collocation"],
    skill: "collocation",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-collocation-deep-concern",
    type: "collocation",
    prompt: "Choose the most natural collocation.",
    instructions: "Pick the word that completes the natural English phrase.",
    target_word: "concern",
    target_word_id: "word-concern",
    question_text: "Which option forms the most natural collocation?",
    sentence_text: "Residents expressed deep concern after the river level rose again overnight.",
    stem: "deep ____",
    exampleSentence:
      "Residents expressed deep concern after the river level rose again overnight.",
    options: [
      { id: "a", label: "concern" },
      { id: "b", label: "window" },
      { id: "c", label: "arrival" },
      { id: "d", label: "texture" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["window", "arrival", "texture"],
    explanation: "Deep concern is a natural and common collocation in English.",
    modality: "mixed",
    difficulty_band: "medium",
    tags: ["collocation"],
    skill: "collocation",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
];
