import type { Exercise } from "./types";

export const mockExercises: Exercise[] = [
  {
    id: "exercise-meaning-match",
    type: "meaning_match",
    prompt: "Choose the best meaning.",
    instructions: "Match the word to its closest meaning.",
    target_word: "intricate",
    target_word_id: "word-intricate",
    question_text: "Which option is the best meaning of 'intricate'?",
    sentence_text: "The machine had an intricate design with many tiny moving parts.",
    sourceLanguageLabel: "English",
    targetLanguageLabel: "Meaning",
    options: [
      { id: "a", label: "highly detailed and complex" },
      { id: "b", label: "very loud" },
      { id: "c", label: "easy to notice" },
      { id: "d", label: "quickly finished" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["very loud", "easy to notice", "quickly finished"],
    pairs: [
      { id: "pair-1", left: "intricate", right: "highly detailed and complex" },
    ],
    explanation: "Intricate usually describes something with many small parts or details.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["meaning", "vocab"],
    skill: "meaning_match",
    metadata: {
      mock: true,
    },
    reviewMeta: {
      attemptCount: 0,
      streak: 0,
      dueAt: null,
    },
  },
  {
    id: "exercise-fill-blank",
    type: "fill_blank",
    prompt: "Fill in the blank.",
    instructions: "Pick the option that best completes the sentence.",
    target_word: "clear",
    target_word_id: "word-clear",
    question_text: "Which option best completes the sentence?",
    sentence_text: "The scientist gave a _____ explanation that made the process easy to follow.",
    clue: "Think about clarity.",
    options: [
      { id: "a", label: "vague" },
      { id: "b", label: "clear" },
      { id: "c", label: "hostile" },
      { id: "d", label: "minor" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["vague", "hostile", "minor"],
    explanation: "A clear explanation is easy to understand, which matches the sentence context.",
    modality: "context",
    difficulty_band: "easy",
    tags: ["cloze", "sentence"],
    skill: "fill_blank",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-context-meaning",
    type: "context_meaning",
    prompt: "What does the highlighted word mean in context?",
    instructions: "Use the sentence, not just the dictionary meaning.",
    target_word: "rugged",
    target_word_id: "word-rugged",
    question_text: "What does 'rugged' mean in this sentence?",
    sentence_text:
      "Although the road looked smooth from a distance, the hikers quickly realized it was rugged and difficult to cross.",
    contextText:
      "Although the road looked smooth from a distance, the hikers quickly realized it was rugged and difficult to cross.",
    focusText: "rugged",
    options: [
      { id: "a", label: "stylish" },
      { id: "b", label: "rough and uneven" },
      { id: "c", label: "covered in water" },
      { id: "d", label: "narrow and crowded" },
    ],
    correct_answer: "b",
    acceptable_answers: ["b"],
    distractors: ["stylish", "covered in water", "narrow and crowded"],
    explanation: "The clue is 'difficult to cross,' which points to rough ground.",
    modality: "context",
    difficulty_band: "hard",
    tags: ["context", "meaning"],
    skill: "context_meaning",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-synonym",
    type: "synonym",
    prompt: "Choose the closest synonym.",
    instructions: "Pick the word with the nearest meaning.",
    target_word: "abandon",
    target_word_id: "word-abandon",
    question_text: "Which option is the closest synonym for 'abandon'?",
    sentence_text: "They had to abandon the plan after the storm changed direction.",
    options: [
      { id: "a", label: "leave behind" },
      { id: "b", label: "repair" },
      { id: "c", label: "balance" },
      { id: "d", label: "measure" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["repair", "balance", "measure"],
    explanation: "Abandon means to leave something behind or give it up.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["synonym"],
    skill: "synonym",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
  {
    id: "exercise-collocation",
    type: "collocation",
    prompt: "Choose the most natural collocation.",
    instructions: "Pick the phrase that sounds most natural in English.",
    target_word: "summary",
    target_word_id: "word-summary",
    question_text: "Which option forms the most natural collocation?",
    sentence_text: "The teacher asked everyone to make a quick summary before class ended.",
    stem: "make a ____",
    exampleSentence: "The teacher asked everyone to make a quick summary before class ended.",
    options: [
      { id: "a", label: "summary" },
      { id: "b", label: "weather" },
      { id: "c", label: "silenceful" },
      { id: "d", label: "arrivaling" },
    ],
    correct_answer: "a",
    acceptable_answers: ["a"],
    distractors: ["weather", "silenceful", "arrivaling"],
    pairs: [{ id: "pair-1", left: "make", right: "summary" }],
    explanation: "Make a summary is a natural verb-noun pairing here.",
    modality: "text",
    difficulty_band: "medium",
    tags: ["collocation"],
    skill: "collocation",
    metadata: {
      mock: true,
    },
    reviewMeta: {},
  },
];
